### ISSUE TITLE
Move zoom relative to touch start

### ISSUE THREAD

**Issue by GiordanoG** [ZoetropeLabs/zoetrope-jquery#41]
Zoom scrolls around relative to center of zoom area rather than touch start, which makes it harder to get to the corners with touch. The zoom method needs changing slightly for touch based zooming.

[original]: Problem dragging the zoomed image - every time the item is touched the zoom starts from the initial position instead of starting from the last position seen.

**Comment by benhowes** [comment]
Yep, I agree with this
